[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "clintool"
version = "0.0.1"
dependencies = [
    "click",
    "requests",
    'importlib-metadata; python_version<"3.10"',
]

[project.scripts]
clint = "clint.main:cli"